# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_gallery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tutorial_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
